### ISSUE TITLE
Flow API related todo list

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-text-field#157]
### Value compatibility

Make sure all public-available user input elements follow these rules:

- [ ] the `value` property is declared as `String`
- [ ] the `value` property is not read-only and allows changes
- [ ] the `value` property declaration has `notify: true`

### Validation compatibility

Make sure all public-available validatable elements follow these rules:

- [ ] the `invalid` property is declared as `Boolean`
- [ ] the `invalid` property has `notify: true`
- [ ] `validate()` method updates the `invalid` state property

### Validation methods

- [ ] mark the `checkValidity()` method with `@returns {boolean}`

### IronFormBehavior-like events

- [ ] mark `iron-form-element-register` and `iron-form-element-unregister` events with `@deprecated` to be removed in next major, since `<iron-form>` v2.0 does not use them, actually.
